apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zechbur.fullname" . }}-config
  labels:
    {{- include "zechbur.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.environment | quote }}
  CORS_ORIGINS: {{ .Values.config.corsOrigins | quote }}
  ACCESS_TOKEN_DAYS: {{ .Values.config.dailyTokenDays | quote }}
  AUTO_MIGRATE: "false"
  AUTO_IMPORT_DICTIONARY: {{ .Values.config.autoImportDictionary | quote }}
  DICTIONARY_PATH: /app/data/udmurt_dictionary_full.json
  TELEGRAM_WEBAPP_URL: {{ .Values.config.publicUrl | quote }}
  API_INTERNAL_URL: http://{{ include "zechbur.fullname" . }}:{{ .Values.service.port }}
