{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "zechbur.fullname" . }}
  labels:
    {{- include "zechbur.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "zechbur.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api
  endpoints:
    - {port: http, path: /metrics, interval: {{ .Values.serviceMonitor.interval }}}
{{- end }}
